src/components/ui/BaseButton.tsx
- Includes JSDoc comments with example usage.
- Supports three built-in variants: primary, secondary, and danger.
- Easily extendable with more styles.
- Handles click events and standard button attributes.
!! Removed 2 filler files "test.ts" from folders.
=> Added BaseButton component for general use.

src/API/fetchApi.ts, src/pages/CheckoutSuccess.tsx, src/pages/Homepage.tsx
I made a fetch function to fetch all the products and console.log the results successfully.
=> made a fetch func for all products console.log successfully

src/App.tsx, src/components/Header.tsx, src/pages/About.tsx, src/pages/Contact.tsx
Responsive navbar with placeholder logo. Not styled yet
=> Made navbar, and updated paths

src/components/CartSidebar.tsx, src/components/Header.tsx, src/types/cartTypes.ts
Ready to insert other functions such as cart items display. Other functions to connect via context functions and display.
Ready for 'bag icon' display for total amount and changing icons for empty state and +1 state.
- Added CartSidebar.tsx component to display content from localStorage. (<= needs context and cart item component)
- Added function to open and close 'CartSidebar'
- cartTypes: added a TS types for CartSidebar
- Responsive to match layout for mobile.
- Minor fix temporarily commented out <img> in header to be able to code. -- Fix above is to merge final Footer to access asset file.
=> Cart sidebar menu, type and functionality

src/components/product/ItemCard.tsx, src/components/product/SearchInput.tsx, src/pages/Homepage.tsx
Made a function for searching products by their names.
=> Search function 

src/components/product/ItemCard.tsx, src/components/product/SearchInput.tsx, src/components/product/SortDropdown.tsx, src/components/product/SortProduct.ts, src/pages/Homepage.tsx
Add function for sorting the products
=> Sorting products

src/components/product/ItemCard.tsx, src/components/product/SearchInput.tsx, src/components/product/SortDropdown.tsx, src/pages/Homepage.tsx
Made sorting dropdown function on the bases of
Low to high price,
High to low price, 
Discounted price high to low 
Low to high
for UI.
=> Sorting dropdown function

src/components/Header.tsx, src/pages/Homepage.tsx
Import the item card on home page.
=> utilize item card on home page

src/components/skeletons/ProductSkeleton.tsx
The ProductSkeleton component provides a placeholder UI that mimics the layout of a product card while the actual data is loading. It uses Tailwind CSS utility classes and the animate-pulse effect to show shimmering gray boxes in place of content.
Key Elements Simulated:
Discount badge (top-left corner)
Product image
Title
Discounted price
Original price
Rating
This enhances user experience by avoiding layout shifts and showing users that content is being fetched.
=> Made an export product skeleton function

src/components/contact/ContactForm.tsx, src/pages/Contact.tsx, src/types/contactTypes.ts
Changes:
Created ContactForm component with validation for name, email, subject, and message
Updated Contact page with form integration and success/error handling
Added TypeScript interfaces for contact form types
Features:
Form validation with error messages
Toast notifications for submission status
Responsive design with Tailwind CSS
=> Implements a functional contact page with form validation and toast notifications.

src/components/product/ItemCard.tsx, src/pages/Homepage.tsx
Import the product skeleton function to home page.
=> import product skeleton to the home page.

src/pages/Homepage.tsx
Add some correction on home page search bar if the product is not matching the criteria it shows a message.
=> Add some correction on home page

src/App.tsx
Fix for remaining imports and use of About page which has been removed.
=> Removed any remaining paths left by last commit

package-lock.json, package.json, src/setupTest.ts, vite.config.ts
=> Install vitest dependencies

src/components/product/SearchInput.test.tsx, src/setupTest.ts
Made searchInput vite testing file. All tests are passed.
=> Made search input vite test

src/pages/Contact.tsx, src/pages/Product.tsx
General styling to error and height to product page and contact page
=> General styling to contact and product page.

README.md, src/pages/CheckoutPaymentDetails.tsx, src/pages/Contact.test.tsx
Removing more commentary text.
Removed "fast checkout" containing payment details of person.
=> Adding README file with content.

src/components/contact/ContactForm.tsx, src/pages/Contact.tsx
Updated the submit button to use the BaseButton imported from /components/ui.
=> submit button update:

src/pages/Homepage.tsx
Add new welcome heading to home page.
=> New heading to home page

src/components/CartSidebar.tsx, src/components/checkout/CCExpiryDateInputs.tsx, src/components/checkout/PersonalInformation.tsx
- divs with no children are now self closing.
- replaced index keys with stable unique values.
- destructured props in PersonalInformation.tsx for cleaner code
=> Updates, based on Feedback from Martin.

src/components/skeletons/ProductSkeleton.tsx, src/components/skeletons/SinglePageSkeleton.tsx, src/context/cart/CartProvider.tsx, src/css/index.css, src/pages/Homepage.tsx
Make use of useCallback to resolve issue in CartProvider.
other minor changes:
- Fix loading indication for search bar at Homepage
- Fix css background issue duplicating the styling.
- ProductSkeleton make all divs with no children selfclosing
- SinglePageSkeleton make all divs with no children selfclosing and adjust setup to match the fully loaded page.
=> feat: Fix issue with infinite render loop fixed caused by userEffect dependency array.
